apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-service
  name: es-service
spec:
  ports:
  - nodePort: 31000
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-deployment
  type: NodePort
