apiVersion: v1
kind: Service
metadata:
  labels:
    app: kib-service
  name: kib-service
  # namespace: default
spec:
  ports:
  - nodePort: 32376
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kib-deployment
  type: NodePort